print("Welcome")
print("hello")"
print("Are you there?")
print("What's up?")
print("I'm fine")
print("Are you ok")
print("I'm not ok")
print("Nothing")
print("Where are you")
print("How are you?")
print("Banana")
print("Apple")
print("Cat")
print("Dog")
print("Elephant")
print("Fan")
print("2")
print("1")
print("3")
print("4")
print("5")
print("6")
print("7")
print("20")
print("8")

